name: codereview-examples

on:
  pull_request:
    types:
      - labeled
      - opened
      - ready_for_review
      - synchronize

concurrency: 
  group: codereview-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  codereview:
    runs-on: ubuntu-latest
    if: >
      github.event.action != 'labeled' &&
      contains(github.event.pull_request.labels.*.name, 'continuous-distribution') ||
      github.event.label.name == 'instant-deployment'
    steps:
      - run: echo '条件分岐用の空ジョブ'
  example-deploygate:
    runs-on: ubuntu-latest
    needs:
      - codereview
    if: >
      contains(github.event.pull_request.labels.*.name, 'deploygate')
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/after-checkout
      - if: github.event.label.name == 'instant-deployment'
        run: gh pr edit '${{ github.event.number }}' --remove-label "instant-deployment"
        env:
          GH_TOKEN: ${{ github.token }}
      - uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 8
          cache: gradle
      - id: build
        run: pxy ./gradlew bundleDebug
      - id: find-artifact
        run: echo "::set-output name=result::$(find app/build/outputs -name "*.aab" -type f | head -1)"
      - id: upload
        uses: jmatsu/dg-upload-app-action@v0.2
        with:
          app_owner_name: red_fat_daruma
          api_token: ${{ secrets.DEPLOYGATE_API_TOKEN }}
          app_file_path: ${{ format('{0}/{1}', github.workspace, steps.find-artifact.outputs.result) }}
          message: |
            Ran ${{ steps.build.outputs.result }} on ${{ github.ref }} / ${{ github.sha }}
            Built by GitHub Actions for code-review
          distribution_find_by: name
          distribution_id: "codereview/${{ github.ref }}"
      - uses: ./.github/actions/post-comment-to-pr-only-once
        with:
          id: codereview-distribution-url
          pull-number: ${{ github.event.number }}
          body: 'Artifacts on this PR being distributed via ${{ steps.upload.outputs.distribution_url }}'
