name: prototype-review-examples

on:
  pull_request:
    types:
      - opened
      - ready_for_review
      - synchronize

concurrency: 
  group: prototype-review-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  prototype-review:
    runs-on: ubuntu-latest
    if: >
      contains(github.event.pull_request.head.ref, 'prototype') &&
      contains(github.event.pull_request.labels.*.name, 'continuous-distribution')
    steps:
      - run: echo '条件分岐用の空ジョブ'

  example-deploygate:
    runs-on: ubuntu-latest
    needs:
      - prototype-review
    if: >
      contains(github.event.pull_request.labels.*.name, 'deploygate')
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/after-checkout
      - uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 8
          cache: gradle
      - id: build
        run: pxy ./gradlew bundleDebug
      - id: find-artifact
        run: echo "::set-output name=result::$(find app/build/outputs -name "*.aab" -type f | head -1)"
      - id: upload
        uses: jmatsu/dg-upload-app-action@v0.2
        with:
          app_owner_name: red_fat_daruma
          api_token: ${{ secrets.DEPLOYGATE_API_TOKEN }}
          app_file_path: ${{ format('{0}/{1}', github.workspace, steps.find-artifact.outputs.result) }}
          message: |
            Ran ${{ steps.build.outputs.result }} on ${{ github.ref }} / ${{ github.sha }}
            Built by GitHub Actions for prototype behavior checking
          distribution_find_by: name
          distribution_id: ${{ github.event.pull_request.head.ref }}

  example-firebase-app-distribution:
    runs-on: ubuntu-latest
    needs:
      - prototype-review
    if: >
      contains(github.event.pull_request.labels.*.name, 'firebase-app-distribution')
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/after-checkout
      - uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 8
          cache: gradle
      - id: build
        run: pxy ./gradlew assembleDebug
      - id: find-artifact
        run: echo "::set-output name=result::$(find app/build/outputs -name "*.apk" -type f | head -1)"
      - id: upload
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.DEBUG_VARIANT_APP_ID }}
          token: ${{ secrets.FIREBASE_CLI_TOKEN }}
          groups: ${{ github.event.pull_request.head.ref }}
          file: ${{ format('{0}/{1}', github.workspace, steps.find-artifact.outputs.result) }}
          releaseNotes: |
            Ran ${{ steps.build.outputs.result }} on ${{ github.ref }} / ${{ github.sha }}
            Built by GitHub Actions for prototype behavior checking
